// Kenyan counties list in order of priority
export const counties = [
  "Nairobi",
  "Mombasa",
  "Kisumu",
  "Nakuru",
  "Nyeri",
  "Baringo",
  "Bomet",
  "Bungoma",
  "Busia",
  "Elgeyo Marakwet",
  "Embu",
  "Garissa",
  "Homa Bay",
  "Isiolo",
  "Kajiado",
  "Kakamega",
  "Kericho",
  "Kiambu",
  "Kilifi",
  "Kirinyaga",
  "Kisii",
  "Kitui",
  "Kwale",
  "Laikipia",
  "Lamu",
  "Machakos",
  "Makueni",
  "Mandera",
  "Marsabit",
  "Meru",
  "Migori",
  "Murang'a",
  "Nandi",
  "Narok",
  "Nyamira",
  "Nyandarua",
  "Samburu",
  "Siaya",
  "Taita Taveta",
  "Tana River",
  "Tharaka Nithi",
  "Trans Nzoia",
  "Turkana",
  "Uasin Gishu",
  "Vihiga",
  "Wajir",
  "West Pokot",
];

// Nairobi routes
export const nairobiRoutes = [
  "Thika Road",
  "Waiyaki Way",
  "Mombasa Road",
  "Jogoo Road",
  "Langata Road",
  "Kiambu Road",
  "Limuru Road",
  "Ngong Road",
  "Diaspora",
  "Argwings Kodhek Road",
];
